# Generated by Django 5.1 on 2026-03-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actuator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='automationrule',
            options={'ordering': ['name']},
        ),
    ]
