# Generated by Django 5.1 on 2026-03-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0002_alter_actuator_options_alter_automationrule_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='automation_rule',
            field=models.ForeignKey(blank=True, help_text='The automation rule that triggered this command, if any', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_commands', to='iot.automationrule'),
        ),
    ]
