# Generated by Django 5.1 on 2026-03-04 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_organization_models'),
        ('iot', '0003_command_automation_rule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='greenhouse',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='greenhouses', to='api.organization'),
        ),
        migrations.AlterField(
            model_name='greenhouse',
            name='owner',
            field=models.ForeignKey(blank=True, help_text='Legacy field — kept for audit. Use organization instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='greenhouses', to=settings.AUTH_USER_MODEL),
        ),
    ]
