# Generated by Django 5.1 on 2026-03-04 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_create_organization_models'),
        ('iot', '0005_migrate_greenhouse_owners_to_orgs'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook'), ('TELEGRAM', 'Telegram')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('email_recipients', models.TextField(blank=True, help_text='Comma-separated email addresses (for EMAIL channel)')),
                ('webhook_url', models.URLField(blank=True, help_text='Target URL (for WEBHOOK channel)')),
                ('webhook_secret', models.CharField(blank=True, help_text='Optional secret for HMAC-SHA256 signature header (for WEBHOOK channel)', max_length=255)),
                ('telegram_bot_token', models.CharField(blank=True, help_text='Telegram Bot API token (for TELEGRAM channel)', max_length=255)),
                ('telegram_chat_id', models.CharField(blank=True, help_text='Telegram chat/group ID (for TELEGRAM channel)', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alert_types', models.JSONField(blank=True, default=list, help_text="List of alert types to match, e.g. ['HIGH','LOW','OFFLINE']. Empty = all.")),
                ('severities', models.JSONField(blank=True, default=list, help_text="List of severities to match, e.g. ['WARNING','CRITICAL']. Empty = all.")),
                ('is_active', models.BooleanField(default=True)),
                ('cooldown_seconds', models.PositiveIntegerField(default=300, help_text='Min seconds between notifications for the same rule')),
                ('last_notified', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='iot.notificationchannel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_rules', to='api.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_logs', to='iot.alert')),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='iot.notificationchannel')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='iot.notificationrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
