# Generated by Django 5.1 on 2026-03-04 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_notification_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReadingHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(help_text='Start of the hour bucket')),
                ('avg_value', models.FloatField()),
                ('min_value', models.FloatField()),
                ('max_value', models.FloatField()),
                ('stddev_value', models.FloatField(default=0.0)),
                ('count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_readings', to='iot.sensor')),
            ],
            options={
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['sensor', '-hour'], name='iot_sensorr_sensor__c46c97_idx')],
                'unique_together': {('sensor', 'hour')},
            },
        ),
    ]
