# Generated by Django 5.0.14 on 2026-03-04 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0007_sensor_reading_hourly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('IDLE', 'Idle'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='IDLE', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='iot.zone')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('schedule_type', models.CharField(choices=[('CRON', 'Cron Expression'), ('TIME_RANGE', 'Daily Time Range')], max_length=12)),
                ('cron_minute', models.CharField(default='0', help_text='Cron minute field', max_length=20)),
                ('cron_hour', models.CharField(default='*', help_text='Cron hour field', max_length=20)),
                ('cron_day_of_week', models.CharField(default='*', help_text='Cron day-of-week (0=Mon..6=Sun) or *', max_length=20)),
                ('start_time', models.TimeField(blank=True, help_text='Start time for TIME_RANGE', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='End time for TIME_RANGE', null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, help_text='List of day-of-week integers (0=Mon..6=Sun) for TIME_RANGE')),
                ('is_active', models.BooleanField(default=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='iot.scenario')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(help_text='Execution order within the scenario (0-based)')),
                ('action', models.CharField(choices=[('ON', 'Turn On'), ('OFF', 'Turn Off'), ('SET', 'Set Value')], max_length=5)),
                ('action_value', models.FloatField(blank=True, help_text='Value for SET commands', null=True)),
                ('delay_seconds', models.PositiveIntegerField(default=0, help_text='Seconds to wait before executing this step')),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='If set, send the reverse action after this many seconds', null=True)),
                ('actuator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_steps', to='iot.actuator')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='iot.scenario')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('scenario', 'order')},
            },
        ),
    ]
