# Generated by Django 5.1 on 2026-03-04 13:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0008_scenario_schedule_scenariostep'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannel',
            name='channel_type',
            field=models.CharField(choices=[('EMAIL', 'Email'), ('WEBHOOK', 'Webhook'), ('TELEGRAM', 'Telegram'), ('PUSH', 'Web Push')], max_length=10),
        ),
        migrations.CreateModel(
            name='PushSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.URLField(max_length=500, unique=True)),
                ('p256dh', models.CharField(help_text='Client public encryption key', max_length=200)),
                ('auth', models.CharField(help_text='Client auth secret', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
