# Generated by Django 5.1 on 2026-03-04 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0009_add_push_subscription_and_push_channel_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('COMMAND', 'Command Sent'), ('EXPORT', 'Data Export')], max_length=10)),
                ('resource_type', models.CharField(help_text="Model name or resource type (e.g. 'Greenhouse', 'Zone', 'Command')", max_length=50)),
                ('resource_id', models.PositiveIntegerField(blank=True, help_text='Primary key of the affected resource', null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description of the action')),
                ('changes', models.JSONField(blank=True, default=dict, help_text='JSON diff of changed fields (old_value → new_value)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='iot_auditev_user_id_b6ef55_idx'), models.Index(fields=['resource_type', 'resource_id'], name='iot_auditev_resourc_d82051_idx'), models.Index(fields=['action', '-created_at'], name='iot_auditev_action_64b69c_idx')],
            },
        ),
    ]
