# Generated by Django 5.1 on 2026-03-05 05:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_create_organization_models"),
        ("iot", "0010_auditevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Icon identifier for the frontend",
                        max_length=50,
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0, help_text="Display order in category list"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "template categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "is_official",
                    models.BooleanField(
                        default=False,
                        help_text="Marked as official Greenhouse template",
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True, help_text="Visible on the marketplace"
                    ),
                ),
                ("version", models.CharField(default="1.0.0", max_length=20)),
                (
                    "changelog",
                    models.TextField(blank=True, help_text="Version changelog"),
                ),
                (
                    "config",
                    models.JSONField(
                        default=dict,
                        help_text="Snapshot of zone configuration: sensors, actuators, automation_rules, scenarios",
                    ),
                ),
                ("avg_rating", models.FloatField(default=0.0)),
                ("rating_count", models.PositiveIntegerField(default=0)),
                ("clone_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        blank=True,
                        help_text="Organization that published this template",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="api.organization",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="templates",
                        to="iot.templatecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-clone_count", "-avg_rating", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TemplateRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "score",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("comment", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ratings",
                        to="iot.template",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="template_ratings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["-avg_rating", "-clone_count"],
                name="iot_templat_avg_rat_5e4d56_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="template",
            index=models.Index(
                fields=["category", "-avg_rating"],
                name="iot_templat_categor_f0f567_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="templaterating",
            unique_together={("template", "user")},
        ),
    ]
