# Generated by Django 5.1 on 2026-03-05 09:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_billing_subscription"),
        ("iot", "0013_sprint23_data_pipeline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("address", models.CharField(blank=True, max_length=500)),
                (
                    "latitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-90.0),
                            django.core.validators.MaxValueValidator(90.0),
                        ]
                    ),
                ),
                (
                    "longitude",
                    models.FloatField(
                        validators=[
                            django.core.validators.MinValueValidator(-180.0),
                            django.core.validators.MaxValueValidator(180.0),
                        ]
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="IANA timezone identifier (e.g. Europe/Paris)",
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="WeatherAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "alert_level",
                    models.CharField(
                        choices=[
                            ("INFO", "Info"),
                            ("WARNING", "Warning"),
                            ("CRITICAL", "Critical"),
                        ],
                        default="WARNING",
                        max_length=10,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "forecast_date",
                    models.DateField(help_text="Date of the forecasted event"),
                ),
                ("is_acknowledged", models.BooleanField(default=False)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WeatherData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(help_text="Time of the weather observation"),
                ),
                (
                    "temperature",
                    models.FloatField(
                        blank=True, help_text="External temperature in °C", null=True
                    ),
                ),
                (
                    "humidity",
                    models.FloatField(
                        blank=True, help_text="Relative humidity in %", null=True
                    ),
                ),
                (
                    "precipitation",
                    models.FloatField(
                        blank=True, help_text="Precipitation in mm", null=True
                    ),
                ),
                (
                    "wind_speed",
                    models.FloatField(
                        blank=True, help_text="Wind speed in km/h", null=True
                    ),
                ),
                (
                    "uv_index",
                    models.FloatField(blank=True, help_text="UV index", null=True),
                ),
                (
                    "cloud_cover",
                    models.FloatField(
                        blank=True, help_text="Cloud cover in %", null=True
                    ),
                ),
                (
                    "weather_code",
                    models.IntegerField(
                        blank=True,
                        help_text="WMO weather interpretation code",
                        null=True,
                    ),
                ),
                (
                    "is_forecast",
                    models.BooleanField(
                        default=False,
                        help_text="True if this is a forecast, False if historical/current",
                    ),
                ),
                ("fetched_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.RenameIndex(
            model_name="sensorreadingdaily",
            new_name="iot_sensorr_sensor__48f90b_idx",
            old_name="iot_sensorrea_sensor__daily_idx",
        ),
        migrations.AddField(
            model_name="site",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sites",
                to="api.organization",
            ),
        ),
        migrations.AddField(
            model_name="greenhouse",
            name="site",
            field=models.ForeignKey(
                blank=True,
                help_text="Geographic site this greenhouse belongs to",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="greenhouses",
                to="iot.site",
            ),
        ),
        migrations.AddField(
            model_name="weatheralert",
            name="acknowledged_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="weatheralert",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_alerts",
                to="iot.site",
            ),
        ),
        migrations.AddField(
            model_name="weatherdata",
            name="site",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="weather_data",
                to="iot.site",
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["site", "-timestamp"], name="iot_weather_site_id_c6da97_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weatherdata",
            index=models.Index(
                fields=["site", "is_forecast", "-timestamp"],
                name="iot_weather_site_id_1b63fd_idx",
            ),
        ),
    ]
