# Generated by Django 5.1 on 2026-03-05 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0016_sprint27_edge_sync"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="auditevent",
            new_name="iot_auditev_cloud_s_424dd1_idx",
            old_name="iot_auditeve_cloud_s_crea_idx",
        ),
        migrations.RenameIndex(
            model_name="sensorreading",
            new_name="iot_sensorr_cloud_s_83af03_idx",
            old_name="iot_sensorre_cloud_s_recv_idx",
        ),
        migrations.RenameIndex(
            model_name="syncbatch",
            new_name="iot_syncbat_edge_de_c5f997_idx",
            old_name="iot_syncbatch_device_start_idx",
        ),
        migrations.RenameIndex(
            model_name="syncbatch",
            new_name="iot_syncbat_status_82584f_idx",
            old_name="iot_syncbatch_status_retry_idx",
        ),
    ]
