# Generated by Django 5.1 on 2026-03-06 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0017_sprint28_cloud_tenant'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growth_status', models.CharField(choices=[('SLOW', 'Slow'), ('NORMAL', 'Normal'), ('FAST', 'Fast'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('gdd_accumulated', models.FloatField(blank=True, help_text='Growing Degree Days accumulated', null=True)),
                ('hydration_status', models.CharField(choices=[('DRY', 'Dry'), ('CORRECT', 'Correct'), ('OPTIMAL', 'Optimal'), ('EXCESS', 'Excess'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('evapotranspiration', models.FloatField(blank=True, help_text='ET₀ mm/day estimate', null=True)),
                ('heat_stress', models.CharField(choices=[('NONE', 'None'), ('LIGHT', 'Light'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('heat_index', models.FloatField(blank=True, help_text='Calculated heat index (°C)', null=True)),
                ('yield_prediction', models.FloatField(blank=True, help_text='Yield prediction score (%)', null=True)),
                ('plant_health_score', models.FloatField(blank=True, help_text='Overall plant health (0-100)', null=True)),
                ('disease_risk', models.CharField(choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('climate_stress', models.CharField(choices=[('NONE', 'None'), ('LIGHT', 'Light'), ('HIGH', 'High'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=10)),
                ('light_level', models.CharField(choices=[('INSUFFICIENT', 'Insufficient'), ('CORRECT', 'Correct'), ('OPTIMAL', 'Optimal'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=15)),
                ('harvest_eta_days', models.IntegerField(blank=True, help_text='Estimated days until harvest', null=True)),
                ('irrigation_needed_liters', models.FloatField(blank=True, help_text='Recommended irrigation (L/plant)', null=True)),
                ('calculated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('zone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_status', to='iot.zone')),
            ],
            options={
                'verbose_name': 'Crop Status',
                'verbose_name_plural': 'Crop Statuses',
            },
        ),
        migrations.CreateModel(
            name='CropIndicatorPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(choices=[('GROWTH', 'Growth'), ('HYDRATION', 'Hydration'), ('HEAT_STRESS', 'Heat Stress'), ('YIELD', 'Yield Prediction'), ('PLANT_HEALTH', 'Plant Health'), ('DISEASE_RISK', 'Disease Risk'), ('CLIMATE_STRESS', 'Climate Stress'), ('LIGHT', 'Light Availability'), ('HARVEST_ETA', 'Harvest ETA'), ('IRRIGATION', 'Irrigation Need')], max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_indicator_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['indicator'],
                'unique_together': {('user', 'indicator')},
            },
        ),
    ]
