# Generated by Django 5.1 on 2026-03-14 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iot", "0019_zone_relay_id_unique_per_greenhouse"),
    ]

    operations = [
        migrations.CreateModel(
            name="FirmwareRelease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Semantic version string (e.g., 3.2.1)",
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("STABLE", "Stable"),
                            ("BETA", "Beta"),
                            ("NIGHTLY", "Nightly"),
                        ],
                        default="STABLE",
                        max_length=10,
                    ),
                ),
                ("release_notes", models.TextField(blank=True)),
                (
                    "binary_url",
                    models.URLField(
                        help_text="URL to the firmware binary", max_length=500
                    ),
                ),
                (
                    "checksum_sha256",
                    models.CharField(
                        help_text="SHA-256 hex digest of the binary", max_length=64
                    ),
                ),
                (
                    "file_size_bytes",
                    models.PositiveIntegerField(help_text="Binary size in bytes"),
                ),
                (
                    "min_hardware_version",
                    models.CharField(
                        blank=True,
                        help_text="Minimum hardware version required (optional)",
                        max_length=30,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceOTAJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("DOWNLOADING", "Downloading"),
                            ("INSTALLING", "Installing"),
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("ROLLED_BACK", "Rolled Back"),
                        ],
                        default="PENDING",
                        max_length=15,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveIntegerField(
                        default=0, help_text="Download/install progress (0–100)"
                    ),
                ),
                (
                    "previous_version",
                    models.CharField(
                        blank=True,
                        help_text="Firmware version before this update",
                        max_length=30,
                    ),
                ),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "edge_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ota_jobs",
                        to="iot.edgedevice",
                    ),
                ),
                (
                    "firmware_release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ota_jobs",
                        to="iot.firmwarerelease",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeviceMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpu_percent", models.FloatField(help_text="CPU usage 0–100")),
                ("memory_percent", models.FloatField(help_text="RAM usage 0–100")),
                ("disk_percent", models.FloatField(help_text="Disk usage 0–100")),
                (
                    "cpu_temperature",
                    models.FloatField(
                        blank=True, help_text="CPU temperature in °C", null=True
                    ),
                ),
                (
                    "uptime_seconds",
                    models.PositiveIntegerField(
                        blank=True, help_text="Device uptime in seconds", null=True
                    ),
                ),
                (
                    "network_latency_ms",
                    models.FloatField(
                        blank=True,
                        help_text="Network latency to cloud in ms",
                        null=True,
                    ),
                ),
                ("recorded_at", models.DateTimeField(db_index=True)),
                (
                    "edge_device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to="iot.edgedevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "Device Metrics",
                "verbose_name_plural": "Device Metrics",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["edge_device", "-recorded_at"],
                        name="iot_devicem_edge_de_fdc580_idx",
                    )
                ],
            },
        ),
    ]
