"""GDPR compliance module: Data Subject Access Request (DSAR) export and right to erasure.

Provides functions to:
- Export all personal data for a user as a JSON bundle.
- Anonymize/erase a user's personal data while preserving aggregate data integrity.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import Any

from django.contrib.auth import get_user_model

User = get_user_model()


def export_user_data(user: Any) -> dict[str, Any]:
    """Export all personal data associated with a user (DSAR).

    Args:
        user: The Django User instance.

    Returns:
        A dict containing all user data, ready for JSON serialization.
    """
    from apps.api.models import Membership, Organization
    from apps.iot.models import (
        Alert,
        Command,
        CropCycle,
        CultureLog,
        Note,
        TraceabilityReport,
    )

    # User profile
    profile = {
        "id": user.pk,
        "username": user.username,
        "email": user.email,
        "first_name": user.first_name,
        "last_name": user.last_name,
        "date_joined": user.date_joined.isoformat() if user.date_joined else None,
        "last_login": user.last_login.isoformat() if user.last_login else None,
    }

    # Organization memberships
    memberships = list(
        Membership.objects.filter(user=user)
        .select_related("organization")
        .values("organization__name", "organization__slug", "role", "joined_at")
    )
    for m in memberships:
        if m.get("joined_at"):
            m["joined_at"] = m["joined_at"].isoformat()

    # Commands created by user
    commands = list(
        Command.objects.filter(created_by=user)
        .values("id", "actuator_id", "command_type", "status", "created_at")
    )
    for c in commands:
        if c.get("created_at"):
            c["created_at"] = c["created_at"].isoformat()

    # Alerts acknowledged by user
    acknowledged_alerts = list(
        Alert.objects.filter(acknowledged_by=user)
        .values("id", "alert_type", "severity", "message", "acknowledged_at")
    )
    for a in acknowledged_alerts:
        if a.get("acknowledged_at"):
            a["acknowledged_at"] = a["acknowledged_at"].isoformat()

    # Crop cycles created by user
    crop_cycles = list(
        CropCycle.objects.filter(created_by=user)
        .values("id", "zone_id", "species", "variety", "status", "created_at")
    )
    for cc in crop_cycles:
        if cc.get("created_at"):
            cc["created_at"] = cc["created_at"].isoformat()

    # Notes authored by user
    notes = list(
        Note.objects.filter(author=user)
        .values("id", "zone_id", "content", "observed_at", "created_at")
    )
    for n in notes:
        for field in ("observed_at", "created_at"):
            if n.get(field):
                n[field] = n[field].isoformat()

    # Culture log entries by user
    culture_logs = list(
        CultureLog.objects.filter(user=user)
        .values("id", "zone_id", "entry_type", "summary", "created_at")
    )
    for cl in culture_logs:
        if cl.get("created_at"):
            cl["created_at"] = cl["created_at"].isoformat()

    # Traceability reports generated by user
    reports = list(
        TraceabilityReport.objects.filter(generated_by=user)
        .values("id", "zone_id", "period_start", "period_end", "sha256_hash", "created_at")
    )
    for r in reports:
        for field in ("period_start", "period_end", "created_at"):
            if r.get(field):
                r[field] = r[field].isoformat() if hasattr(r[field], "isoformat") else str(r[field])

    return {
        "export_date": datetime.now(timezone.utc).isoformat(),
        "user": profile,
        "memberships": memberships,
        "commands": commands,
        "acknowledged_alerts": acknowledged_alerts,
        "crop_cycles": crop_cycles,
        "notes": notes,
        "culture_logs": culture_logs,
        "traceability_reports": reports,
    }


def anonymize_user(user: Any) -> dict[str, int]:
    """Anonymize a user's personal data (right to erasure / right to be forgotten).

    This does NOT delete the user account but replaces all personal identifiers
    with anonymized values. Aggregate data and system logs are preserved for
    data integrity purposes.

    Args:
        user: The Django User instance to anonymize.

    Returns:
        A dict with counts of affected records per category.
    """
    from apps.iot.models import Command, CropCycle, CultureLog, Note, TraceabilityReport

    anonymous_id = f"anon_{user.pk}"
    counts: dict[str, int] = {}

    # Anonymize user profile
    user.username = anonymous_id
    user.email = f"{anonymous_id}@deleted.local"
    user.first_name = ""
    user.last_name = ""
    user.is_active = False
    user.set_unusable_password()
    user.save()
    counts["user_profile"] = 1

    # Nullify FK references on commands
    cmd_count = Command.objects.filter(created_by=user).update(created_by=None)
    counts["commands"] = cmd_count

    # Nullify FK references on crop cycles
    cc_count = CropCycle.objects.filter(created_by=user).update(created_by=None)
    counts["crop_cycles"] = cc_count

    # Anonymize notes: remove author but keep content for traceability
    note_count = Note.objects.filter(author=user).update(author=None)
    counts["notes"] = note_count

    # Nullify FK references on culture logs
    cl_count = CultureLog.objects.filter(user=user).update(user=None)
    counts["culture_logs"] = cl_count

    # Nullify FK on traceability reports
    tr_count = TraceabilityReport.objects.filter(generated_by=user).update(generated_by=None)
    counts["traceability_reports"] = tr_count

    return counts
