#!/usr/bin/env bash
# onboard_client.sh — Bootstrap a new Greenhouse edge client on a Raspberry Pi.
#
# This script:
#   1. Registers the device with the Cloud CRM API (requires ADMIN JWT token)
#   2. Writes the generated credentials to /etc/greenhouse/.env
#   3. Optionally pulls the latest docker-compose.prod.yml and starts the stack
#
# Usage:
#   export CLOUD_URL="https://cloud.your-domain.com"
#   export ADMIN_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."   # ADMIN or OWNER JWT
#   export ORG_SLUG="my-farm"
#   export DEVICE_NAME="Raspberry Pi Site Nord"
#   bash onboard_client.sh
#
# Or pass arguments:
#   bash onboard_client.sh --cloud-url https://cloud.your-domain.com \
#                          --token $ADMIN_TOKEN \
#                          --org my-farm \
#                          --name "Raspberry Pi Site Nord"

set -euo pipefail

# ---------------------------------------------------------------------------
# Defaults / env vars
# ---------------------------------------------------------------------------

CLOUD_URL="${CLOUD_URL:-}"
ADMIN_TOKEN="${ADMIN_TOKEN:-}"
ORG_SLUG="${ORG_SLUG:-}"
DEVICE_NAME="${DEVICE_NAME:-Raspberry Pi $(hostname)}"
ENV_DIR="/etc/greenhouse"
ENV_FILE="$ENV_DIR/.env"
COMPOSE_FILE="docker-compose.prod.yml"
GITHUB_RAW="https://raw.githubusercontent.com/your-org/greenhouse-saas/main"

# ---------------------------------------------------------------------------
# Parse flags
# ---------------------------------------------------------------------------

while [[ $# -gt 0 ]]; do
  case $1 in
    --cloud-url) CLOUD_URL="$2"; shift 2 ;;
    --token)     ADMIN_TOKEN="$2"; shift 2 ;;
    --org)       ORG_SLUG="$2"; shift 2 ;;
    --name)      DEVICE_NAME="$2"; shift 2 ;;
    *) echo "Unknown flag: $1"; exit 1 ;;
  esac
done

# ---------------------------------------------------------------------------
# Validation
# ---------------------------------------------------------------------------

if [[ -z "$CLOUD_URL" || -z "$ADMIN_TOKEN" || -z "$ORG_SLUG" ]]; then
  echo "ERROR: Missing required variables."
  echo "  CLOUD_URL, ADMIN_TOKEN, ORG_SLUG must all be set."
  echo "  See script header for usage instructions."
  exit 1
fi

command -v curl >/dev/null 2>&1 || { echo "curl is required but not installed."; exit 1; }
command -v jq   >/dev/null 2>&1 || { echo "jq is required. Install: apt-get install -y jq"; exit 1; }

echo "==> Registering device '$DEVICE_NAME' for org '$ORG_SLUG' on $CLOUD_URL ..."

# ---------------------------------------------------------------------------
# Step 1: Register device via API
# ---------------------------------------------------------------------------

RESPONSE=$(curl -sf -X POST \
  "$CLOUD_URL/api/edge/register/" \
  -H "Authorization: Bearer $ADMIN_TOKEN" \
  -H "Content-Type: application/json" \
  -d "{\"org_slug\": \"$ORG_SLUG\", \"name\": \"$DEVICE_NAME\"}" \
  )

if [[ -z "$RESPONSE" ]]; then
  echo "ERROR: Empty response from cloud API. Check CLOUD_URL and ADMIN_TOKEN."
  exit 1
fi

DEVICE_ID=$(echo "$RESPONSE" | jq -r '.device_id')
SECRET_KEY=$(echo "$RESPONSE" | jq -r '.secret_key')

if [[ "$DEVICE_ID" == "null" || -z "$DEVICE_ID" ]]; then
  echo "ERROR: Failed to parse device_id from response:"
  echo "$RESPONSE"
  exit 1
fi

echo "==> Device registered successfully."
echo "    Device ID:  $DEVICE_ID"
echo "    Secret Key: (hidden — will be written to $ENV_FILE)"

# ---------------------------------------------------------------------------
# Step 2: Write credentials to /etc/greenhouse/.env
# ---------------------------------------------------------------------------

sudo mkdir -p "$ENV_DIR"
sudo chmod 700 "$ENV_DIR"

cat <<EOF | sudo tee "$ENV_FILE" > /dev/null
# Generated by onboard_client.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT COMMIT THIS FILE

# App mode
EDGE_MODE=True
CLOUD_MODE=False
DJANGO_SETTINGS_MODULE=config.settings.production

# Edge device credentials
EDGE_DEVICE_ID=$DEVICE_ID
EDGE_SECRET_KEY=$SECRET_KEY
CLOUD_SYNC_URL=$CLOUD_URL

# Sync schedule
CLOUD_SYNC_BATCH_SIZE=500
CLOUD_SYNC_TIMEOUT=30

# Database (fill in)
POSTGRES_DB=greenhouse
POSTGRES_USER=greenhouse
POSTGRES_PASSWORD=CHANGE_ME
DATABASE_URL=postgresql://greenhouse:CHANGE_ME@postgres:5432/greenhouse

# Redis
REDIS_URL=redis://redis:6379/0

# Django
DJANGO_SECRET_KEY=$(python3 -c "import secrets; print(secrets.token_hex(32))" 2>/dev/null || openssl rand -hex 32)
DJANGO_DEBUG=False
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1

# MQTT (local broker on edge)
MQTT_BROKER=mosquitto
MQTT_PORT=1883
EOF

sudo chmod 600 "$ENV_FILE"
echo "==> Credentials written to $ENV_FILE"

# ---------------------------------------------------------------------------
# Step 3: Optional — pull docker-compose.prod.yml and start
# ---------------------------------------------------------------------------

echo ""
read -r -p "==> Pull and start the Greenhouse edge stack now? [y/N] " START_STACK
if [[ "$START_STACK" =~ ^[Yy]$ ]]; then
  WORK_DIR="/opt/greenhouse"
  sudo mkdir -p "$WORK_DIR"
  echo "==> Downloading docker-compose.prod.yml to $WORK_DIR ..."
  sudo curl -sf "$GITHUB_RAW/docker-compose.prod.yml" -o "$WORK_DIR/$COMPOSE_FILE"
  sudo cp "$ENV_FILE" "$WORK_DIR/.env"

  echo "==> Starting the stack (this may take a few minutes on first run) ..."
  cd "$WORK_DIR"
  sudo docker compose -f "$COMPOSE_FILE" up -d

  echo "==> Stack started. Verify with: docker compose -f $COMPOSE_FILE logs -f"
else
  echo ""
  echo "==> Manual setup:"
  echo "    1. Copy $ENV_FILE to your project directory as .env"
  echo "    2. Run: docker compose -f docker-compose.prod.yml up -d"
fi

# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------

echo ""
echo "========================================="
echo " Onboarding complete!"
echo "========================================="
echo " Organization:  $ORG_SLUG"
echo " Device Name:   $DEVICE_NAME"
echo " Device ID:     $DEVICE_ID"
echo " Cloud URL:     $CLOUD_URL"
echo " Credentials:   $ENV_FILE"
echo "========================================="
echo " Next steps:"
echo "   - Edit $ENV_FILE to set POSTGRES_PASSWORD and other values"
echo "   - The device will sync to cloud every 5 minutes automatically"
echo "   - Check sync status at $CLOUD_URL/administration/sync"
echo "========================================="
